version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: responsivas-db
    restart: always
    environment:
      POSTGRES_USER: juan
      POSTGRES_PASSWORD: claveSegura123
      POSTGRES_DB: responsivas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: