version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: responsivas-db
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:${PGPORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: